---
name: Update nixpkgs
on:
  workflow_dispatch:
  schedule:
    - cron: "10 4 * * 1"

jobs:
  lockfile:
    name: Update Nix lockfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Update Nix lockfile
        run: nix flake lock --update-input nixpkgs
      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          add-paths: flake.lock
          branch: nix/flake-lock-update
          labels: dependencies
          commit-message: "build: flake.lock automated update"
          title: "build: nixpkgs update"
          body: ""
